; ----------------------------------
; Measures
; ----------------------------------

[MeasureAudioOutDelay_L00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=0

[MeasureAudioOutDelay_L01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=1

[MeasureAudioOutDelay_L02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=2

[MeasureAudioOutDelay_L03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=3

[MeasureAudioOutDelay_L04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=4

[MeasureAudioOutDelay_L05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=5

[MeasureAudioOutDelay_L06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=6

[MeasureAudioOutDelay_L07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=7

[MeasureAudioOutDelay_L08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=8

[MeasureAudioOutDelay_L09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=9

[MeasureAudioOutDelay_L10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=10

[MeasureAudioOutDelay_L11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=11

[MeasureAudioOutDelay_L12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=12

[MeasureAudioOutDelay_L13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=13

[MeasureAudioOutDelay_L14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=14

[MeasureAudioOutDelay_L15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=15

[MeasureAudioOutDelay_L16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=16

[MeasureAudioOutDelay_L17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=17

[MeasureAudioOutDelay_L18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=18

[MeasureAudioOutDelay_L19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=19

[MeasureAudioOutDelay_L20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=20

[MeasureAudioOutDelay_L21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=21

[MeasureAudioOutDelay_L22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=22

[MeasureAudioOutDelay_L23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=L
Type=Band
BandIdx=23

[MeasureAudioOutDelay_R00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=0

[MeasureAudioOutDelay_R01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=1

[MeasureAudioOutDelay_R02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=2

[MeasureAudioOutDelay_R03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=3

[MeasureAudioOutDelay_R04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=4

[MeasureAudioOutDelay_R05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=5

[MeasureAudioOutDelay_R06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=6

[MeasureAudioOutDelay_R07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=7

[MeasureAudioOutDelay_R08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=8

[MeasureAudioOutDelay_R09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=9

[MeasureAudioOutDelay_R10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=10

[MeasureAudioOutDelay_R11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=11

[MeasureAudioOutDelay_R12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=12

[MeasureAudioOutDelay_R13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=13

[MeasureAudioOutDelay_R14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=14

[MeasureAudioOutDelay_R15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=15

[MeasureAudioOutDelay_R16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=16

[MeasureAudioOutDelay_R17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=17

[MeasureAudioOutDelay_R18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=18

[MeasureAudioOutDelay_R19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=19

[MeasureAudioOutDelay_R20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=20

[MeasureAudioOutDelay_R21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=21

[MeasureAudioOutDelay_R22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=22

[MeasureAudioOutDelay_R23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOutDelay
Channel=R
Type=Band
BandIdx=23

; ----------------------------------
; Meters
; ----------------------------------

[OutFFT_L_Delay_00]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
X=#BarLX#
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L00]))
[OutFFT_L_Delay_01]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L01]))
[OutFFT_L_Delay_02]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L02]))
[OutFFT_L_Delay_03]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L03]))
[OutFFT_L_Delay_04]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L04]))
[OutFFT_L_Delay_05]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L05]))
[OutFFT_L_Delay_06]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L06]))
[OutFFT_L_Delay_07]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L07]))
[OutFFT_L_Delay_08]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L08]))
[OutFFT_L_Delay_09]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L09]))
[OutFFT_L_Delay_10]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L10]))
[OutFFT_L_Delay_11]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L11]))
[OutFFT_L_Delay_12]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L12]))
[OutFFT_L_Delay_13]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L13]))
[OutFFT_L_Delay_14]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L14]))
[OutFFT_L_Delay_15]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L15]))
[OutFFT_L_Delay_16]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L16]))
[OutFFT_L_Delay_17]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L17]))
[OutFFT_L_Delay_18]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L18]))
[OutFFT_L_Delay_19]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L19]))
[OutFFT_L_Delay_20]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L20]))
[OutFFT_L_Delay_21]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L21]))
[OutFFT_L_Delay_22]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L22]))
[OutFFT_L_Delay_23]
Meter=Image
MeterStyle=StyleOutFFT_L_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_L23]))


[OutFFT_R_Delay_00]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
X=#BarRX#
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R00]))

[OutFFT_R_Delay_01]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R01]))
[OutFFT_R_Delay_02]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R02]))
[OutFFT_R_Delay_03]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R03]))
[OutFFT_R_Delay_04]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R04]))
[OutFFT_R_Delay_05]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R05]))
[OutFFT_R_Delay_06]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R06]))
[OutFFT_R_Delay_07]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R07]))
[OutFFT_R_Delay_08]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R08]))
[OutFFT_R_Delay_09]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R09]))
[OutFFT_R_Delay_10]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R10]))
[OutFFT_R_Delay_11]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R11]))
[OutFFT_R_Delay_12]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R12]))
[OutFFT_R_Delay_13]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R13]))
[OutFFT_R_Delay_14]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R14]))
[OutFFT_R_Delay_15]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R15]))
[OutFFT_R_Delay_16]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R16]))
[OutFFT_R_Delay_17]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R17]))
[OutFFT_R_Delay_18]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R18]))
[OutFFT_R_Delay_19]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R19]))
[OutFFT_R_Delay_20]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R20]))
[OutFFT_R_Delay_21]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R21]))
[OutFFT_R_Delay_22]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R22]))
[OutFFT_R_Delay_23]
Meter=Image
MeterStyle=StyleOutFFT_R_Delay
Y=(#DelayY#+#H#*(1-[MeasureAudioOutDelay_R23]))