; ----------------------------------
; Measures
; ----------------------------------

[MeasureAudioOut_RMS_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=RMS

[MeasureAudioOut_RMS_R]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=RMS

[MeasureAudioOut_Peak_L]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Peak

[MeasureAudioOut_Peak_R]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Peak

[MeasureAudioOut_L00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=0

[MeasureAudioOut_L01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=1

[MeasureAudioOut_L02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=2

[MeasureAudioOut_L03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=3

[MeasureAudioOut_L04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=4

[MeasureAudioOut_L05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=5

[MeasureAudioOut_L06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=6

[MeasureAudioOut_L07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=7

[MeasureAudioOut_L08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=8

[MeasureAudioOut_L09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=9

[MeasureAudioOut_L10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=10

[MeasureAudioOut_L11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=11

[MeasureAudioOut_L12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=12

[MeasureAudioOut_L13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=13

[MeasureAudioOut_L14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=14

[MeasureAudioOut_L15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=15

[MeasureAudioOut_L16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=16

[MeasureAudioOut_L17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=17

[MeasureAudioOut_L18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=18

[MeasureAudioOut_L19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=19

[MeasureAudioOut_L20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=20

[MeasureAudioOut_L21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=21

[MeasureAudioOut_L22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=22

[MeasureAudioOut_L23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=L
Type=Band
BandIdx=23

[MeasureAudioOut_R00]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=0

[MeasureAudioOut_R01]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=1

[MeasureAudioOut_R02]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=2

[MeasureAudioOut_R03]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=3

[MeasureAudioOut_R04]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=4

[MeasureAudioOut_R05]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=5

[MeasureAudioOut_R06]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=6

[MeasureAudioOut_R07]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=7

[MeasureAudioOut_R08]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=8

[MeasureAudioOut_R09]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=9

[MeasureAudioOut_R10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=10

[MeasureAudioOut_R11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=11

[MeasureAudioOut_R12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=12

[MeasureAudioOut_R13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=13

[MeasureAudioOut_R14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=14

[MeasureAudioOut_R15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=15

[MeasureAudioOut_R16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=16

[MeasureAudioOut_R17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=17

[MeasureAudioOut_R18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=18

[MeasureAudioOut_R19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=19

[MeasureAudioOut_R20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=20

[MeasureAudioOut_R21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=21

[MeasureAudioOut_R22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=22

[MeasureAudioOut_R23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudioOut
Channel=R
Type=Band
BandIdx=23

; ----------------------------------
; Meters
; ----------------------------------

[OutFFT_L_00]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L23
X=#BarLX#
Y=#BarLY#
[OutFFT_L_01]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L22
[OutFFT_L_02]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L21
[OutFFT_L_03]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L20
[OutFFT_L_04]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L19
[OutFFT_L_05]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L18
[OutFFT_L_06]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L17
[OutFFT_L_07]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L16
[OutFFT_L_08]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L15
[OutFFT_L_09]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L14
[OutFFT_L_10]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L13
[OutFFT_L_11]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L12
[OutFFT_L_12]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L11
[OutFFT_L_13]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L10
[OutFFT_L_14]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L09
[OutFFT_L_15]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L08
[OutFFT_L_16]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L07
[OutFFT_L_17]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L06
[OutFFT_L_18]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L05
[OutFFT_L_19]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L04
[OutFFT_L_20]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L03
[OutFFT_L_21]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L02
[OutFFT_L_22]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L01
[OutFFT_L_23]
Meter=Bar
MeterStyle=StyleOutFFT_L
MeasureName=MeasureAudioOut_L00


[OutFFT_R_00]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R00
X=#BarRX#
Y=#BarRY#
[OutFFT_R_01]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R01
[OutFFT_R_02]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R02
[OutFFT_R_03]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R03
[OutFFT_R_04]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R04
[OutFFT_R_05]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R05
[OutFFT_R_06]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R06
[OutFFT_R_07]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R07
[OutFFT_R_08]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R08
[OutFFT_R_09]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R09
[OutFFT_R_10]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R10
[OutFFT_R_11]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R11
[OutFFT_R_12]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R12
[OutFFT_R_13]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R13
[OutFFT_R_14]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R14
[OutFFT_R_15]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R15
[OutFFT_R_16]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R16
[OutFFT_R_17]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R17
[OutFFT_R_18]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R18
[OutFFT_R_19]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R19
[OutFFT_R_20]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R20
[OutFFT_R_21]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R21
[OutFFT_R_22]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R22
[OutFFT_R_23]
Meter=Bar
MeterStyle=StyleOutFFT_R
MeasureName=MeasureAudioOut_R23