#include "AppConfig.h"

#include "juce_core/juce_core.cpp"
#include "juce_events/juce_events.cpp"
#include "juce_data_structures/juce_data_structures.cpp"
#include "juce_graphics/juce_graphics.cpp"
#include "juce_gui_basics/juce_gui_basics.cpp"
#include "juce_gui_extra/juce_gui_extra.cpp"
#include "juce_audio_basics/juce_audio_basics.cpp"
#include "juce_audio_formats/juce_audio_formats.cpp"
#include "juce_audio_devices/juce_audio_devices.cpp"
#include "juce_audio_processors/juce_audio_processors.cpp"
#include "juce_audio_utils/juce_audio_utils.cpp"
#include "juce_cryptography/juce_cryptography.cpp"
#include "juce_opengl/juce_opengl.cpp"
#include "juce_video/juce_video.cpp"
// #include "box2d/box2d.cpp"
